server:
  port: 9001
  servlet:
    context-path: /
logging:
  level:
    com.hugo.manta: debug

spring:
  devtools:
    restart:
      enabled: true
    add-properties: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.153.215:3306/manta?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: hugo1234

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

